// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "李明",
            "email": "2572597150@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refreshToken": {
            "get": {
                "tags": [
                    "鉴权"
                ],
                "summary": "刷新token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.AuthError"
                        }
                    }
                }
            }
        },
        "/captcha/confirm": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "校验图片验证码",
                "parameters": [
                    {
                        "description": "图片验证码的id和值",
                        "name": "ConfirmCaptcha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfirmCaptcha"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CaptchaToken"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/captcha/get": {
            "get": {
                "tags": [
                    "鉴权"
                ],
                "summary": "获取图片验证码id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetCaptchaResp"
                        }
                    }
                }
            }
        },
        "/captcha/{{.captcha_id}}.png": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "获取或刷新图片验证码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "时间戳或随机数",
                        "name": "reload",
                        "in": "query"
                    }
                ]
            }
        },
        "/email/confirm": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "验证邮箱验证码",
                "parameters": [
                    {
                        "description": "邮箱验证码和图片验证码的token",
                        "name": "ConfirmEmailCode",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfirmEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/email/send": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "图片验证码返回的token和邮件地址",
                        "name": "SendEmailCode",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SendEmailCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/group/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置分组"
                ],
                "summary": "添加配置分组",
                "parameters": [
                    {
                        "description": "分组数据",
                        "name": "AddConfigGroup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddConfigGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/group/delete": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置分组"
                ],
                "summary": "删除配置分组",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分组id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/group/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置分组"
                ],
                "summary": "编辑配置分组",
                "parameters": [
                    {
                        "description": "配置分组修改项",
                        "name": "EditConfigGroup",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditConfigGroupReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/group/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "配置分组"
                ],
                "summary": "获取配置分组列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "环境 Dev:开发环境 Test:测试环境 Pre:预发布环境 Prod:正式环境",
                        "name": "env",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetConfigGroupResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录的账号和密码",
                        "name": "Login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.AuthError"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "tags": [
                    "鉴权"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "添加项目",
                "parameters": [
                    {
                        "description": "添加项目数据",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/delete": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目创建者",
                        "name": "project_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "获取项目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ProjectInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "编辑项目",
                "parameters": [
                    {
                        "description": "编辑项目数据",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "获取项目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员",
                        "name": "admin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目所属部门",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目的开发人员",
                        "name": "develop_user",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_index",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目创建者",
                        "name": "project_user",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetProjectListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/user/auth2Info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户第三方应用信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Auth2UserInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/user/avatar/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "上传用户头像",
                "parameters": [
                    {
                        "description": "multipart/form-data加密后的文件内容",
                        "name": "UpdateAvatar",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/user/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取用户信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "注册账号",
                "parameters": [
                    {
                        "description": "注册用户的信息",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Register"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/user/update": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "description": "更新用户信息",
                        "name": "UpdateUserInfo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateUserInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AddConfigGroupReq": {
            "type": "object",
            "required": [
                "env",
                "group_name",
                "project_id"
            ],
            "properties": {
                "comment": {
                    "description": "分组备注",
                    "type": "string"
                },
                "env": {
                    "description": "环境",
                    "type": "string"
                },
                "group_name": {
                    "description": "分组名",
                    "type": "string"
                },
                "project_id": {
                    "description": "项目id",
                    "type": "integer"
                }
            }
        },
        "model.AddProject": {
            "type": "object",
            "required": [
                "name",
                "project_user"
            ],
            "properties": {
                "admin": {
                    "description": "管理员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "department": {
                    "description": "项目所属部门",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "develop_user": {
                    "description": "项目的开发人员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "project_user": {
                    "description": "项目创建者",
                    "type": "string"
                }
            }
        },
        "model.Auth2UserInfo": {
            "type": "object",
            "properties": {
                "github_avatar": {
                    "description": "github 头像",
                    "type": "string"
                },
                "github_username": {
                    "description": "github 昵称",
                    "type": "string"
                },
                "qq_avatar": {
                    "description": "qq 头像",
                    "type": "string"
                },
                "qq_username": {
                    "description": "qq 昵称",
                    "type": "string"
                },
                "wechat_avatar": {
                    "description": "微信头像",
                    "type": "string"
                },
                "wechat_username": {
                    "description": "微信昵称",
                    "type": "string"
                },
                "weibo_avatar": {
                    "description": "微博头像",
                    "type": "string"
                },
                "weibo_username": {
                    "description": "微博昵称",
                    "type": "string"
                }
            }
        },
        "model.AuthError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "http 状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        },
        "model.CaptchaToken": {
            "type": "object",
            "properties": {
                "captcha_token": {
                    "description": "图片验证码验证成功返回的token",
                    "type": "string"
                }
            }
        },
        "model.ConfigGroup": {
            "type": "object",
            "properties": {
                "comment": {
                    "description": "分组备注",
                    "type": "string"
                },
                "group_name": {
                    "description": "分组名称",
                    "type": "string"
                },
                "id": {
                    "description": "分组id",
                    "type": "integer"
                }
            }
        },
        "model.ConfirmCaptcha": {
            "type": "object",
            "required": [
                "captcha_id",
                "captcha_solution"
            ],
            "properties": {
                "captcha_id": {
                    "description": "验证码id",
                    "type": "string"
                },
                "captcha_solution": {
                    "description": "验证码的值",
                    "type": "string"
                }
            }
        },
        "model.ConfirmEmail": {
            "type": "object",
            "required": [
                "captcha_token",
                "email_code"
            ],
            "properties": {
                "captcha_token": {
                    "description": "图片验证码验证成功返回的token",
                    "type": "string"
                },
                "email_code": {
                    "description": "邮箱验证码",
                    "type": "string"
                }
            }
        },
        "model.EditConfigGroupReq": {
            "type": "object",
            "required": [
                "group_name",
                "id",
                "project_id"
            ],
            "properties": {
                "comment": {
                    "description": "分组备注",
                    "type": "string"
                },
                "group_name": {
                    "description": "分组名",
                    "type": "string"
                },
                "id": {
                    "description": "分组id",
                    "type": "integer"
                },
                "project_id": {
                    "description": "项目id",
                    "type": "integer"
                }
            }
        },
        "model.EditProject": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "admin": {
                    "description": "管理员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "department": {
                    "description": "项目所属部门",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "develop_user": {
                    "description": "项目的开发人员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "项目id",
                    "type": "integer"
                }
            }
        },
        "model.GetCaptchaResp": {
            "type": "object",
            "properties": {
                "captcha_id": {
                    "description": "验证码id",
                    "type": "string"
                }
            }
        },
        "model.GetConfigGroupResp": {
            "type": "object",
            "properties": {
                "config_group": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ConfigGroup"
                    }
                }
            }
        },
        "model.GetProjectListResp": {
            "type": "object",
            "properties": {
                "project_list": {
                    "description": "项目列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ProjectInfo"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "model.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "model.LoginResp": {
            "type": "object",
            "properties": {
                "expire": {
                    "description": "过期时间",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                }
            }
        },
        "model.ProjectInfo": {
            "type": "object",
            "properties": {
                "admin": {
                    "description": "管理员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "create_time": {
                    "description": "项目创建时间",
                    "type": "string"
                },
                "department": {
                    "description": "项目所属部门",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "develop_user": {
                    "description": "项目的开发人员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "项目id",
                    "type": "integer"
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "project_user": {
                    "description": "项目创建者",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "model.Register": {
            "type": "object",
            "required": [
                "email_address",
                "password",
                "username"
            ],
            "properties": {
                "email_address": {
                    "description": "邮箱地址",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "model.SendEmailCode": {
            "type": "object",
            "required": [
                "captcha_token",
                "email_address"
            ],
            "properties": {
                "captcha_token": {
                    "description": "图片验证码验证成功返回的token",
                    "type": "string"
                },
                "email_address": {
                    "description": "邮箱地址",
                    "type": "string"
                }
            }
        },
        "model.UpdateUserInfo": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别 1 男 2 女",
                    "type": "integer"
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "电话号码",
                    "type": "string"
                },
                "region": {
                    "description": "地区",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "model.UserInfo": {
            "type": "object",
            "properties": {
                "create_project": {
                    "description": "创建的项目",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "create_time": {
                    "description": "注册时间",
                    "type": "string"
                },
                "develop_project": {
                    "description": "参与的项目",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "email": {
                    "description": "邮箱",
                    "type": "string"
                },
                "gender": {
                    "description": "性别 1 男 2 女",
                    "type": "integer"
                },
                "manage_project": {
                    "description": "管理的项目",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "nickname": {
                    "description": "用户昵称",
                    "type": "string"
                },
                "phone": {
                    "description": "电话号码",
                    "type": "string"
                },
                "photo": {
                    "description": "头像",
                    "type": "string"
                },
                "region": {
                    "description": "地区",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "services.WebResponse": {
            "type": "object",
            "properties": {
                "errcode": {
                    "description": "错误码",
                    "type": "integer"
                },
                "errmsg": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "配置平台",
	Description: "配置管理平台 HTTP接口文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
