// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "李明",
            "email": "2572597150@qq.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refreshToken": {
            "get": {
                "tags": [
                    "鉴权"
                ],
                "summary": "刷新token",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.AuthError"
                        }
                    }
                }
            }
        },
        "/captcha/confirm": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "校验图片验证码",
                "parameters": [
                    {
                        "description": "校验图片验证码",
                        "name": "ConfirmCaptcha",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.ConfirmCaptcha"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/captcha/get": {
            "get": {
                "tags": [
                    "鉴权"
                ],
                "summary": "获取图片验证码id",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetCaptchaResp"
                        }
                    }
                }
            }
        },
        "/captcha/{{.captcha_id}}.png": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "获取或刷新图片验证码",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "时间戳或随机数",
                        "name": "reload",
                        "in": "query"
                    }
                ]
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "鉴权"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "description": "登录的账号和密码",
                        "name": "Login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.AuthError"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "tags": [
                    "鉴权"
                ],
                "summary": "登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/project/add": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "添加项目",
                "parameters": [
                    {
                        "description": "添加项目数据",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AddProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/delete": {
            "delete": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "删除项目",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目创建者",
                        "name": "project_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "获取项目详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ProjectInfo"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/edit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "编辑项目",
                "parameters": [
                    {
                        "description": "编辑项目数据",
                        "name": "project",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EditProject"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/project/list": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "项目"
                ],
                "summary": "获取项目列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "管理员",
                        "name": "admin",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目所属部门",
                        "name": "department",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目的开发人员",
                        "name": "develop_user",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "项目id",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "项目名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page_index",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "项目创建者",
                        "name": "project_user",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.GetProjectListResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "注册账号",
                "parameters": [
                    {
                        "description": "注册用户的账号密码",
                        "name": "Register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/services.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AddProject": {
            "type": "object",
            "required": [
                "name",
                "project_user"
            ],
            "properties": {
                "admin": {
                    "description": "管理员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "department": {
                    "description": "项目所属部门",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "develop_user": {
                    "description": "项目的开发人员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "project_user": {
                    "description": "项目创建者",
                    "type": "string"
                }
            }
        },
        "model.AuthError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "model.ConfirmCaptcha": {
            "type": "object",
            "required": [
                "captcha_id",
                "captcha_solution"
            ],
            "properties": {
                "captcha_id": {
                    "description": "验证码id",
                    "type": "string"
                },
                "captcha_solution": {
                    "description": "验证码的值",
                    "type": "string"
                }
            }
        },
        "model.EditProject": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "admin": {
                    "description": "管理员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "department": {
                    "description": "项目所属部门",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "develop_user": {
                    "description": "项目的开发人员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "项目id",
                    "type": "integer"
                }
            }
        },
        "model.GetCaptchaResp": {
            "type": "object",
            "properties": {
                "captcha_id": {
                    "description": "验证码id",
                    "type": "string"
                }
            }
        },
        "model.GetProjectListResp": {
            "type": "object",
            "properties": {
                "projectList": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ProjectInfo"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.LoginReq": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "username": {
                    "description": "用户名",
                    "type": "string"
                }
            }
        },
        "model.LoginResp": {
            "type": "object",
            "properties": {
                "expire": {
                    "description": "过期时间",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                }
            }
        },
        "model.ProjectInfo": {
            "type": "object",
            "properties": {
                "admin": {
                    "description": "管理员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "create_time": {
                    "description": "项目创建时间",
                    "type": "string"
                },
                "department": {
                    "description": "项目所属部门",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "description": {
                    "description": "项目描述",
                    "type": "string"
                },
                "develop_user": {
                    "description": "项目的开发人员",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "description": "项目id",
                    "type": "integer"
                },
                "name": {
                    "description": "项目名称",
                    "type": "string"
                },
                "project_user": {
                    "description": "项目创建者",
                    "type": "string"
                },
                "update_time": {
                    "description": "更新时间",
                    "type": "string"
                }
            }
        },
        "services.WebResponse": {
            "type": "object",
            "properties": {
                "errcode": {
                    "description": "错误码",
                    "type": "integer"
                },
                "errmsg": {
                    "description": "错误信息",
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "配置平台",
	Description: "配置平台 HTTP接口文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
