definitions:
  model.AddProject:
    properties:
      admin:
        description: 管理员
        items:
          type: string
        type: array
      department:
        description: 项目所属部门
        items:
          type: string
        type: array
      description:
        description: 项目描述
        type: string
      develop_user:
        description: 项目的开发人员
        items:
          type: string
        type: array
      name:
        description: 项目名称
        type: string
      project_user:
        description: 项目创建者
        type: string
    required:
    - name
    - project_user
    type: object
  model.EditProject:
    properties:
      admin:
        description: 管理员
        items:
          type: string
        type: array
      department:
        description: 项目所属部门
        items:
          type: string
        type: array
      description:
        description: 项目描述
        type: string
      develop_user:
        description: 项目的开发人员
        items:
          type: string
        type: array
      id:
        description: 项目id
        type: integer
    required:
    - id
    type: object
  model.GetProjectListResp:
    properties:
      projectList:
        items:
          $ref: '#/definitions/model.ProjectInfo'
        type: array
      total:
        type: integer
    type: object
  model.ProjectInfo:
    properties:
      admin:
        description: 管理员
        items:
          type: string
        type: array
      create_time:
        description: 项目创建时间
        type: string
      department:
        description: 项目所属部门
        items:
          type: string
        type: array
      description:
        description: 项目描述
        type: string
      develop_user:
        description: 项目的开发人员
        items:
          type: string
        type: array
      id:
        description: 项目id
        type: integer
      name:
        description: 项目名称
        type: string
      project_user:
        description: 项目创建者
        type: string
      update_time:
        description: 更新时间
        type: string
    type: object
  services.LoginReq:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  services.Token:
    properties:
      expire:
        description: 过期时间
        type: integer
      token:
        description: token
        type: string
    type: object
  services.WebResponse:
    properties:
      errcode:
        description: 错误码
        type: integer
      errmsg:
        description: 错误信息
        type: string
    type: object
info:
  contact:
    email: 2572597150@qq.com
    name: 李明
  description: 配置平台 HTTP接口文档
  title: 配置平台
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录用户的账号密码
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/services.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 登录
      tags:
      - 鉴权
  /project/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 添加项目数据
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/model.AddProject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 添加项目
      tags:
      - 项目
  /project/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 项目id
        in: query
        name: id
        required: true
        type: integer
      - description: 项目创建者
        in: query
        name: project_user
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 删除项目
      tags:
      - 项目
  /project/detail:
    get:
      consumes:
      - application/json
      parameters:
      - description: 项目id
        in: query
        name: id
        required: true
        type: integer
      - description: 项目名称
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProjectInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 获取项目详情
      tags:
      - 项目
  /project/edit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 编辑项目数据
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/model.EditProject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 编辑项目
      tags:
      - 项目
  /project/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 管理员
        in: query
        name: admin
        type: string
      - description: 项目所属部门
        in: query
        name: department
        type: string
      - description: 项目的开发人员
        in: query
        name: develop_user
        type: string
      - description: 项目id
        in: query
        name: id
        type: integer
      - description: 项目名称
        in: query
        name: name
        type: string
      - description: 页码
        in: query
        name: page_index
        required: true
        type: integer
      - description: 页大小
        in: query
        name: page_size
        required: true
        type: integer
      - description: 项目创建者
        in: query
        name: project_user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetProjectListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 获取项目列表
      tags:
      - 项目
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册用户的账号密码
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/services.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 注册账号
      tags:
      - 鉴权
swagger: "2.0"
