definitions:
  model.AddConfigGroupReq:
    properties:
      comment:
        description: 分组备注
        type: string
      env:
        description: 环境
        type: string
      group_name:
        description: 分组名
        type: string
      project_id:
        description: 项目id
        type: integer
    required:
    - env
    - group_name
    - project_id
    type: object
  model.AddProject:
    properties:
      admin:
        description: 管理员
        items:
          type: string
        type: array
      department:
        description: 项目所属部门
        items:
          type: string
        type: array
      description:
        description: 项目描述
        type: string
      develop_user:
        description: 项目的开发人员
        items:
          type: string
        type: array
      name:
        description: 项目名称
        type: string
      project_user:
        description: 项目创建者
        type: string
    required:
    - name
    - project_user
    type: object
  model.Auth2UserInfo:
    properties:
      github_avatar:
        description: github 头像
        type: string
      github_username:
        description: github 昵称
        type: string
      qq_avatar:
        description: qq 头像
        type: string
      qq_username:
        description: qq 昵称
        type: string
      wechat_avatar:
        description: 微信头像
        type: string
      wechat_username:
        description: 微信昵称
        type: string
      weibo_avatar:
        description: 微博头像
        type: string
      weibo_username:
        description: 微博昵称
        type: string
    type: object
  model.AuthError:
    properties:
      code:
        description: http 状态码
        type: integer
      message:
        description: 错误信息
        type: string
    type: object
  model.CaptchaToken:
    properties:
      captcha_token:
        description: 图片验证码验证成功返回的token
        type: string
    type: object
  model.ConfigGroup:
    properties:
      comment:
        description: 分组备注
        type: string
      group_name:
        description: 分组名称
        type: string
      id:
        description: 分组id
        type: integer
    type: object
  model.ConfirmCaptcha:
    properties:
      captcha_id:
        description: 验证码id
        type: string
      captcha_solution:
        description: 验证码的值
        type: string
    required:
    - captcha_id
    - captcha_solution
    type: object
  model.ConfirmEmail:
    properties:
      captcha_token:
        description: 图片验证码验证成功返回的token
        type: string
      email_code:
        description: 邮箱验证码
        type: string
    required:
    - captcha_token
    - email_code
    type: object
  model.EditConfigGroupReq:
    properties:
      comment:
        description: 分组备注
        type: string
      group_name:
        description: 分组名
        type: string
      id:
        description: 分组id
        type: integer
      project_id:
        description: 项目id
        type: integer
    required:
    - group_name
    - id
    - project_id
    type: object
  model.EditProject:
    properties:
      admin:
        description: 管理员
        items:
          type: string
        type: array
      department:
        description: 项目所属部门
        items:
          type: string
        type: array
      description:
        description: 项目描述
        type: string
      develop_user:
        description: 项目的开发人员
        items:
          type: string
        type: array
      id:
        description: 项目id
        type: integer
    required:
    - id
    type: object
  model.GetCaptchaResp:
    properties:
      captcha_id:
        description: 验证码id
        type: string
    type: object
  model.GetConfigGroupResp:
    properties:
      config_group:
        items:
          $ref: '#/definitions/model.ConfigGroup'
        type: array
    type: object
  model.GetProjectListResp:
    properties:
      project_list:
        description: 项目列表
        items:
          $ref: '#/definitions/model.ProjectInfo'
        type: array
      total:
        description: 总数
        type: integer
    type: object
  model.LoginReq:
    properties:
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  model.LoginResp:
    properties:
      expire:
        description: 过期时间
        type: string
      token:
        description: token
        type: string
    type: object
  model.ProjectInfo:
    properties:
      admin:
        description: 管理员
        items:
          type: string
        type: array
      create_time:
        description: 项目创建时间
        type: string
      department:
        description: 项目所属部门
        items:
          type: string
        type: array
      description:
        description: 项目描述
        type: string
      develop_user:
        description: 项目的开发人员
        items:
          type: string
        type: array
      id:
        description: 项目id
        type: integer
      name:
        description: 项目名称
        type: string
      project_user:
        description: 项目创建者
        type: string
      update_time:
        description: 更新时间
        type: string
    type: object
  model.Register:
    properties:
      email_address:
        description: 邮箱地址
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - email_address
    - password
    - username
    type: object
  model.SendEmailCode:
    properties:
      captcha_token:
        description: 图片验证码验证成功返回的token
        type: string
      email_address:
        description: 邮箱地址
        type: string
    required:
    - captcha_token
    - email_address
    type: object
  model.UpdateUserInfo:
    properties:
      email:
        description: 邮箱
        type: string
      gender:
        description: 性别 1 男 2 女
        type: integer
      nickname:
        description: 用户昵称
        type: string
      phone:
        description: 电话号码
        type: string
      region:
        description: 地区
        type: string
      username:
        description: 用户名
        type: string
    type: object
  model.UserInfo:
    properties:
      create_project:
        description: 创建的项目
        items:
          type: string
        type: array
      create_time:
        description: 注册时间
        type: string
      develop_project:
        description: 参与的项目
        items:
          type: string
        type: array
      email:
        description: 邮箱
        type: string
      gender:
        description: 性别 1 男 2 女
        type: integer
      manage_project:
        description: 管理的项目
        items:
          type: string
        type: array
      nickname:
        description: 用户昵称
        type: string
      phone:
        description: 电话号码
        type: string
      photo:
        description: 头像
        type: string
      region:
        description: 地区
        type: string
      username:
        description: 用户名
        type: string
    type: object
  services.WebResponse:
    properties:
      errcode:
        description: 错误码
        type: integer
      errmsg:
        description: 错误信息
        type: string
    type: object
info:
  contact:
    email: 2572597150@qq.com
    name: 李明
  description: 配置管理平台 HTTP接口文档
  title: 配置平台
  version: "1.0"
paths:
  /auth/refreshToken:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AuthError'
      summary: 刷新token
      tags:
      - 鉴权
  /captcha/{{.captcha_id}}.png:
    get:
      consumes:
      - application/json
      parameters:
      - description: 时间戳或随机数
        in: query
        name: reload
        type: integer
      summary: 获取或刷新图片验证码
      tags:
      - 鉴权
  /captcha/confirm:
    post:
      consumes:
      - application/json
      parameters:
      - description: 图片验证码的id和值
        in: body
        name: ConfirmCaptcha
        required: true
        schema:
          $ref: '#/definitions/model.ConfirmCaptcha'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CaptchaToken'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 校验图片验证码
      tags:
      - 鉴权
  /captcha/get:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetCaptchaResp'
      summary: 获取图片验证码id
      tags:
      - 鉴权
  /email/confirm:
    post:
      consumes:
      - application/json
      parameters:
      - description: 邮箱验证码和图片验证码的token
        in: body
        name: ConfirmEmailCode
        required: true
        schema:
          $ref: '#/definitions/model.ConfirmEmail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 验证邮箱验证码
      tags:
      - 鉴权
  /email/send:
    post:
      consumes:
      - application/json
      parameters:
      - description: 图片验证码返回的token和邮件地址
        in: body
        name: SendEmailCode
        required: true
        schema:
          $ref: '#/definitions/model.SendEmailCode'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 发送邮箱验证码
      tags:
      - 鉴权
  /group/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 分组数据
        in: body
        name: AddConfigGroup
        required: true
        schema:
          $ref: '#/definitions/model.AddConfigGroupReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 添加配置分组
      tags:
      - 配置分组
  /group/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 分组id
        in: query
        name: id
        required: true
        type: integer
      - description: 项目id
        in: query
        name: project_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 删除配置分组
      tags:
      - 配置分组
  /group/edit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 配置分组修改项
        in: body
        name: EditConfigGroup
        required: true
        schema:
          $ref: '#/definitions/model.EditConfigGroupReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 编辑配置分组
      tags:
      - 配置分组
  /group/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 环境 Dev:开发环境 Test:测试环境 Pre:预发布环境 Prod:正式环境
        in: query
        name: env
        required: true
        type: string
      - description: 项目id
        in: query
        name: project_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetConfigGroupResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 获取配置分组列表
      tags:
      - 配置分组
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录的账号和密码
        in: body
        name: Login
        required: true
        schema:
          $ref: '#/definitions/model.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.LoginResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.AuthError'
      summary: 登录
      tags:
      - 鉴权
  /logout:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 登出
      tags:
      - 鉴权
  /project/add:
    post:
      consumes:
      - application/json
      parameters:
      - description: 添加项目数据
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/model.AddProject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 添加项目
      tags:
      - 项目
  /project/delete:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 项目id
        in: query
        name: id
        required: true
        type: integer
      - description: 项目创建者
        in: query
        name: project_user
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 删除项目
      tags:
      - 项目
  /project/detail:
    get:
      consumes:
      - application/json
      parameters:
      - description: 项目id
        in: query
        name: id
        required: true
        type: integer
      - description: 项目名称
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProjectInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 获取项目详情
      tags:
      - 项目
  /project/edit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 编辑项目数据
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/model.EditProject'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 编辑项目
      tags:
      - 项目
  /project/list:
    get:
      consumes:
      - application/json
      parameters:
      - description: 管理员
        in: query
        name: admin
        type: string
      - description: 项目所属部门
        in: query
        name: department
        type: string
      - description: 项目的开发人员
        in: query
        name: develop_user
        type: string
      - description: 项目id
        in: query
        name: id
        type: integer
      - description: 项目名称
        in: query
        name: name
        type: string
      - description: 页码
        in: query
        name: page_index
        required: true
        type: integer
      - description: 页大小
        in: query
        name: page_size
        required: true
        type: integer
      - description: 项目创建者
        in: query
        name: project_user
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.GetProjectListResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 获取项目列表
      tags:
      - 项目
  /user/auth2Info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Auth2UserInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 获取用户第三方应用信息
      tags:
      - 用户管理
  /user/avatar/update:
    post:
      consumes:
      - application/json
      parameters:
      - description: multipart/form-data加密后的文件内容
        in: body
        name: UpdateAvatar
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 上传用户头像
      tags:
      - 用户管理
  /user/info:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.UserInfo'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 获取用户信息
      tags:
      - 用户管理
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册用户的信息
        in: body
        name: Register
        required: true
        schema:
          $ref: '#/definitions/model.Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 注册账号
      tags:
      - 用户管理
  /user/update:
    post:
      parameters:
      - description: 更新用户信息
        in: body
        name: UpdateUserInfo
        required: true
        schema:
          $ref: '#/definitions/model.UpdateUserInfo'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.WebResponse'
      summary: 更新用户信息
      tags:
      - 用户管理
swagger: "2.0"
