// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Auth2       string
	ConfigGroup string
	ConfigItem  string
	Project     string
	Seaweedfs   string
	Test        string
	User        string
}{
	Auth2:       "auth2",
	ConfigGroup: "config_group",
	ConfigItem:  "config_item",
	Project:     "project",
	Seaweedfs:   "seaweedfs",
	Test:        "test",
	User:        "user",
}
