// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Project   string
	Seaweedfs string
	User      string
}{
	Project:   "project",
	Seaweedfs: "seaweedfs",
	User:      "user",
}
